stages:
  extract:
    cmd: python scripts/01_extract.py
    deps:
    - data/inputs/Casos_Diarios_Estado_Nacional_Confirmados.csv
    - data/inputs/Casos_Diarios_Estado_Nacional_Defunciones.csv
    - data/inputs/Casos_Diarios_Estado_Nacional_Negativos.csv
    - scripts/01_extract.py
    outs:
    - data/processed/casos_covid.csv
  prepare:
    cmd: python scripts/02_prepare.py
    deps:
    - data/processed/casos_covid.csv
    - scripts/02_prepare.py
    outs:
    - data/processed/covid_prepared.csv
  model:
    cmd: python scripts/03_model.py
    deps:
    - data/processed/covid_prepared.csv
    - scripts/03_model.py
    outs:
    - data/processed/covid_trend.csv
  results:
    cmd: python scripts/04_results.py
    deps:
    - data/processed/covid_trend.csv
    - scripts/04_results.py
    outs:
    - data/processed/results/trend_results.json
